

                                      _______________

                                         OmegaPlus
                                      _______________



 OmegaPlus version 3.0.0 released by Nikolaos Alachiotis and Pavlos Pavlidis in December 2014.


 Command:

	 ./OmegaPlus -name S -input ../ALL.chr1.phase3_shapeit2_mvncall_integrated_v5.20130502.genotypes.vcf -grid 10000 -minwin 1000 -maxwin 200000 -seed 12345



 Input file format (0:ms, 1:fasta, 2:macs, 3:vcf, 4:sf):	3
 Gap (-) imputation:						OFF
 Ambiguous character (N) imputation:				OFF
 Omega search strategy:						Exhaustive
 Alignment deduction to binary:					OFF
 Total number of samples in the VCF:				2504
 Samples excluded from the analysis:				0


 Alignment 1
		Sequences:		5008
		Sites:			6195844

		WARNING: Maximum window (-maxwin) has changed to 115052

		Processing (seconds) - starts at 4739.137087:	421900.212824

		Max Omega:		396171.531250
		Location:		149445280.00
		Leftmost SNP:		149433322
		Rightmost SNP:		149448635


 Total elapsed time 421901.592324 seconds.


